# Use the official Prometheus Pushgateway image as the base image
FROM prom/pushgateway:latest

# Expose the default Pushgateway port
EXPOSE 9091

# Default command to run the Pushgateway
CMD ["--web.listen-address=:9091"]