name: Pushgateway Proxy
language: python
variables:
  - name: PUSHGATEWAY_URL
    inputType: FreeText
    description: Service url to the Prometheus push gateway.
    defaultValue: prometheus-pushgateway:80
    required: true
  - name: PUSHGATEWAY_PROXY_PASSWORD
    inputType: Secret
    description: Prometheus push gateway proxy password.
    defaultValue: pushgateway_proxy_password
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: http-api-sample
