{
 "title": "Processing metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "workspace_id",
    "query": {
     "query": "label_values(events_processed_total,workspace_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Events processed per environment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(workspace_id) (rate(events_processed_total[1m]))",
     "legendFormat": "{{workspace_id}}"
    }
   ]
  },
  {
   "title": "Total events processed per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(events_processed_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events processed per application in environment: ${workspace_id}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(consumer_group) (rate(events_processed_total{workspace_id=\"${workspace_id}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}