name: grafana-2
language: docker
variables:
  - name: GF_SECURITY_ADMIN_PASSWORD
    inputType: Secret
    description: Password for the admin user
    defaultValue: grafana_admin_pw
    required: true
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: The optional InfluxDB Token to use
    defaultValue: grafana_admin_pw
dockerfile: dockerfile
defaultFile: dockerfile
libraryItemId: grafana
